### PR TITLE
Host-And-Join-Functional-endpoints_HASEEB-KHALIL

### PR DESCRIPTION
**Pull request by Haseeb3927**
The host can create a random code to share with users. They can join the energiser page using the join button and 7 digit code provided by the host. They will see a synced timer that will display the same time to everyone.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have carefully reviewed my own code
- [x] I have commented my code
- [x] I have updated any documentation

### CODE REVIEW

**Review by ademalagoz — APPROVED** [review]
Thanks

**Review by ademalagoz — APPROVED** [review]
Thanks 2 👍 :)

**Review by justsealan — APPROVED** [review]
great work!

**Comment by ademalagoz** [comment]
Great job @Haseeb3927

**Pull request merged**
